DROP TABLE IF EXISTS wordles;

CREATE TABLE wordles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator TEXT NOT NULL,
    word TEXT NOT NULL,
    topic TEXT NOT NULL
);